# Generated by Django 5.1 on 2024-08-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('store_location', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('itemized_purchases', models.TextField(blank=True, null=True)),
                ('receipt_category', models.CharField(blank=True, max_length=100, null=True)),
                ('keywords_tags', models.CharField(blank=True, max_length=255, null=True)),
                ('scan_date', models.DateField(blank=True, null=True)),
                ('scanned_image', models.ImageField(upload_to='receipts/')),
                ('ocr_data', models.TextField(blank=True, null=True)),
                ('vendor_contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_identification_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_identification_numbers', models.CharField(blank=True, max_length=100, null=True)),
                ('regulatory_details', models.TextField(blank=True, null=True)),
                ('notes_comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
